# docker-compose -f docker-compose.yml up >> run the command
version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    container_name: store
    volumes:
      - ./data/storepostgres:/var/lib/postgresql/data
      - ./psql.sh:/docker-entrypoint-initdb.d/psql.sh

